name: Generate Diagrams

on:
  push:
    paths: [ '**.plantuml' ]
    branches: [ "main" ]
  pull_request:
    paths: [ '**.plantuml' ]
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ./generate_diagrams.sh
        run: |
          chmod +x ./generate_diagrams.sh
          ./generate_diagrams.sh
        shell: bash